Added pandas to requirements of tutorial template doc
quantumblacklabs/kedro pull request #543
Opened 2020-10-04 12:25 UTC by csaranbalaji

## Description

Resolves #527
Updated dependencies in tutorial template documentation

## Development notes

None, only docs/source updated.

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

2020-10-04 19:56 UTC, deepyaman requested changes

2020-10-04 19:56 UTC, deepyaman commented on docs/source/03_tutorial/02_tutorial_template.md
>  kedro==0.16.5
```suggestion
```
This line is no longer necessary.

2020-10-04 19:59 UTC, deepyaman commented
Can you reword "Resolves #527" in your description, so it doesn't auto-close the issue. :) I think the issue encompasses a bit more work.

2020-10-05 03:52 UTC, deepyaman approved these changes

2020-10-05 08:31 UTC, MerelTheisenQB approved these changes
Thanks for contributing this fix 🙂

2020-10-05 09:07 UTC, DmitriiDeriabinQB approved these changes

2020-10-05 09:55 UTC, merged